# Generated by Django 5.0.6 on 2024-07-03 19:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="videos/",
            ),
        ),
    ]
